packages:
  - "packages/*"
  - "!packages/connectors"
  - "packages/connectors/*"
  - "!packages/docs"
  - "!packages/components"
  - "packages/components/*"
  - "packages/**/examples/*"
  - "!packages/antd"
  - "packages/antd/*"