packages:
  - "packages/*"
  - "!packages/inputs"
  - "!packages/connectors"
  - "!packages/components"
  - "packages/inputs/*"
  - "packages/connectors/*"
  - "packages/components/*"
  - "packages/**/examples/*"